services:

  haproxy:
    image: haproxy:3.0-alpine
    container_name: loadbalancer
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"

  api1:
    image: guilhermegules/fraud-detector-rinha
    container_name: api1
    environment:
      - SERVER_PORT=8080
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160MB"

  api2:
    image: guilhermegules/fraud-detector-rinha
    container_name: api2
    environment:
      - SERVER_PORT=8080
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160MB"

networks:
  default:
    driver: bridge