services:

  haproxy:
    image: haproxy:3.0-alpine
    container_name: loadbalancer
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy

  api1:
    image: guilhermegules/fraud-detector-rinha
    container_name: api1
    environment:
      - SERVER_PORT=8080
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160MB"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/ready" ]
      interval: 3s
      timeout: 10s
      retries: 10

  api2:
    image: guilhermegules/fraud-detector-rinha
    container_name: api2
    environment:
      - SERVER_PORT=8080
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160MB"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/ready" ]
      interval: 3s
      timeout: 10s
      retries: 10

networks:
  default:
    driver: bridge