spring:
  application:
    name: frauddetector
  threads:
    virtual:
      enabled: true
server:
  tomcat:
    threads:
      max: 32
      min-spare: 4
    max-connections: 512
    accept-count: 128
    connection-timeout: 30s
    max-swallow-size: -1
