spring:
  application:
    name: frauddetector
server:
  tomcat:
    threads:
      max: 200
      min-spare: 20
    max-connections: 500
    accept-count: 200
    connection-timeout: 30s
    max-swallow-size: -1
