x-api: &api
  image: guilhermegules/fraud-detector-rinha:latest
  environment:
    - SERVER_PORT=8080
  mem_limit: 160m
  cpus: "0.45"
  healthcheck:
    test: ["CMD", "curl", "-sf", "http://localhost:8080/ready"]
    interval: 5s
    timeout: 3s
    retries: 3
    start_period: 10s
  networks:
    - rinha-net

services:

  haproxy:
    image: haproxy:3.0-alpine
    container_name: loadbalancer
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    mem_limit: 30m
    cpus: "0.1"
    networks:
      - rinha-net
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy

  api1:
    <<: *api
    container_name: api1

  api2:
    <<: *api
    container_name: api2

networks:
  rinha-net:
    driver: bridge
