x-api: &api
  image: guilhermegules/fraud-detector-rinha:latest
  environment:
    - SERVER_PORT=8080
  deploy:
    resources:
      limits:
        cpus: "0.45"
        memory: "160MB"


services:

  haproxy:
    image: haproxy:3.0-alpine
    container_name: loadbalancer
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"
    depends_on:
      - api1
      - api2

  api1:
    <<: *api
    container_name: api1

  api2:
    <<: *api
    container_name: api2

networks:
  default:
    driver: bridge